name: mapnstreet
channels:
  - conda-forge
dependencies:
  # app requirements
  - cartopy
  # download/process requirements
  - grpcio
  - pip
  - pip:
    # app requirements
    - panel
    - geoviews
    - holoviews
    - geopandas
    - shapely
    - fugue
    - duckdb
    - fastparquet
    # download/process requirements
    - ray
    - bs4
    - tqdm
